version: 0.1
log:
  level: info
  formatter: text
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
notifications:
  endpoints:
    - name: XXX-ENDPOINT_NAME-XXX
      url: XXX-ENDPOINT_URL-XXX
      timeout: XXX-ENDPOINT_TIMEOUT-XXXms
      threshold: XXX-ENDPOINT_THRESHOLD-XXX
      backoff: XXX-ENDPOINT_BACKOFF-XXXs
